# ==============================
# = SERVER
# ==============================
server.port=5555

# ==============================
# = DATABASE (PostgreSQL)
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5000/modi
spring.datasource.username=postgres
spring.datasource.password=passport
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# = JPA / HIBERNATE
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ==============================
# = SWAGGER
# ==============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

# ==============================
# = SECURITY
# ==============================
spring.security.filter.dispatcher-types=REQUEST,ASYNC,ERROR

# ==============================
# = LOGGING
# ==============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
